### PR TITLE
Bump pdfbox from 2.0.26 to 3.0.0

### PR DESCRIPTION
**Pull request by sz-liva**
pdfbox has been recently updated to version 3.0.0 which is not backwards compatible with 2.0.x.
This pull request introduces the necessary changes to make boxable compatible with pdfbox 3.0.0.

### CODE REVIEW

**Comment by sz-liva** [comment]
@dhorions , @johnmanko Please, review.

**Review by giboow — APPROVED** [review]

**Comment by sz-liva** [comment]
Who can merge it, make a new release and publish it to Maven Central Repository?

**Comment by sz-liva** [comment]
It requires a premium access. I can't find any other channel to contact him.

**Comment by giboow** [comment]
Just see his github profile and then his personnal website : https://quodlibet.be/

**Comment by johnmanko** [comment]
I merged, but I don't have access to do a maven release.

**Comment by sz-liva** [comment]
I wrote to @dhorions on LinkedIn 10 days ago bug he didn't answer.

**Pull request merged**
