### PR TITLE
Update Tokenizer.java

### PR DESCRIPTION
**Pull request by krishnakant-sarda-abzooba**
Support HTML <s> tag

### CODE REVIEW

**Comment by Frulenzo** [comment]
Can you provide some valid test case or just PDF output of this implementation?

**Comment by Frulenzo** [comment]
Do you have some valid test cases for supporting this tag?

**Comment by Cotyteam** [comment]
No. Been a couple of months since I worked on it.

**Comment by Frulenzo** [comment]
When you can provide some test examples please reopen PR

**Pull request closed without merging**
