### PR TITLE
bugfix: proper removing top border in table

### PR DESCRIPTION
**Pull request by Frulenzo**
Solution for issue #48

Output
[bugfix.pdf](https://github.com/dhorions/boxable/files/216862/bugfix.pdf)

### CODE REVIEW

**Comment by dhorions** [comment]
Could you add a test for this situation to the test cases before I merge it?

**Comment by Frulenzo** [comment]
Here you go :) I'm sorry for not participating in making documentation but I promise I will try my best in next few days. Can you please drop one more time your email adress because I can't find it anymore in old issue thread.

**Comment by Frulenzo** [comment]
It's solved only missing top border but it doesn't solve main problem: when cell height is bigger than your canvas height. That must be implement in a way that we enable "breaking" cells.

**Comment by borgogelli** [comment]
The problem persists in master and in 1.5-rc release

image

**Comment by Frulenzo** [comment]
Hi @borgogelli ,
Can you please provide some test with dummy data so I can recreate your case?

**Pull request merged**
