### PR TITLE
Issue #120: Add support for setting hyperlink URL on a Cell

### PR DESCRIPTION
**Pull request by lambart**
Just contributing back some changes made for my employer. I see this has also been requested as issue #120.

Call `Cell.setUrl()` to add a URI to your Cell; it will be rendered and clickable in the enclosing Table.

### CODE REVIEW

**Comment by JamJar00** [comment]
Would love to see this get merged! Would be a great bit of functionality to have available so we can remove long links from our PDFs

**Comment by vivaca77** [comment]
> 

hi lambart, can you please give an example how to use it, I see your implementation is used as createImageCell, not sure if is possible using it as regular cell and just using text?

**Comment by johnmanko** [comment]
@lambart / @JamJar00 

Can you give me a little background on this?  Is a cell URI a standard feature of PDFBox?

**Comment by JamJar00** [comment]
I'm not sure I understand the question, it's not a 'standard' feature because PDFBox doesn't natively support tables. That's why we use boxable 🙂 

This is a quality of life change. IIRC currently you need to have the full link text in the cell (which then automatically hyperlinks in most readers) where as this would allow you to have some 'click here' text that takes you somewhere when you click the cell.

**Comment by theeogflip** [comment]
We need this, its actual not possible to add a hyperlink to a Cell

**Comment by johnmanko** [comment]
I'll take a look at this PR this weekend.  Hopefully we can get it merged and put out a new release.

**Comment by johnmanko** [comment]
@JamJar00 Do you have a test you can include with this?

**Comment by theeogflip** [comment]
Test is here: https://github.com/dhorions/boxable/pull/262

**Comment by lambart** [comment]
> > 
> 
> hi lambart, can you please give an example how to use it, I see your implementation is used as createImageCell, not sure if is possible using it as regular cell and just using text?

Hi vivica77, sorry for the slow response!

For our purposes, we have only used it in an `ImageCell`; I haven't tried it in a `TableCell` but it might work.

We just do something like this...
```
imageCell.setUrl(new URL("https://example.com"));
```

I'm happy to see this getting some traction, and that some people find it useful.

**Comment by lambart** [comment]
> @lambart / @JamJar00
> 
> Can you give me a little background on this? Is a cell URI a standard feature of PDFBox?

Hi John,
PFBox has various classes which extend `PDAction`, with support for form manipulation, navigation etc. We're just using one of those, a `PDActionURI`, to make PDFBox provide a navigable hyperlink for any arbitrary URL.

**Pull request merged**
