### PR TITLE
Update Tokenizer.java

### PR DESCRIPTION
**Pull request by krishnakant-sarda-abzooba**
Support HTML "u" <u>tag</u>

### CODE REVIEW

**Comment by Frulenzo** [comment]
Can you provide some valid test case or just PDF output of this implementation?

**Comment by Frulenzo** [comment]
Another bump. Do you have some test cases for this?

**Comment by Cotyteam** [comment]
No. Been a couple of months since I worked on it.

**Comment by Frulenzo** [comment]
When you can provide some test examples please reopen PR show us little test case with PDF output.

**Pull request closed without merging**
