### PR TITLE
Solves problem # 108

### PR DESCRIPTION
**Pull request by CSchemmy**
Solves problem # 108

### CODE REVIEW

**Comment by CSchemmy** [comment]
Thanks to all the contributors for the good work.

**Comment by dobluth** [comment]
Hi!

Thanks for all the effort!

Just wanted to quickly mention one thing about adding the dependency to logback. I have thought about this a while ago, and came to the conclusion that this should not be added.  This has a simple reason: when adding this dependency, each user of Boxable will include logback as a transitive dependency, unless manually excluded. If someone is already using another implementation of the logging API, you force him to take some manual effort to fix the build setup right after updating to a new version of Boxable. I think this is very inconvenient and should be avoided. Never force anyone to use a specific implementation of an API.

It's been a long time since I looked into the code, and I don't fully remember everything, so this could be wrong. But can we maybe restrict this to the test scope?

Regards,
Markus

**Comment by CSchemmy** [comment]
The only place where the logger is used is in the FontUtils class for the exeption treatment. This class is not part of the test. Thus, anyone who uses the current API and does not want to ignore the error messages from SLF4J will have to solve this problem.
If we replace this with System.err.println (), we can do without the dependencies for the logger. But then these outputs are only visible in the console and would be missing in a log file.
Do you have a better idea to avoid dependency?

**Comment by CSchemmy** [comment]
Another way is to change the logging in the modul FontUtils from org.slf4j to the logger used in PDType0Font. So the dependency can be completely eliminated I will prepare this change and then offer to merge.

**Pull request closed without merging**
